# Jekyll Defaults
title: Allan98's Blog
description: Allan's first blog at 2016-05.
baseurl: "" # the subpath of your site, e.g. /blog

# About/contact
url: "https://Allan98.github.io"
github: https://github.com/allan98

#Others
timezone: Asiz/Shanghai
markdown: kramdown
highlighter: rouge
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: feed.xml
tags_path: tag.html

navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
